<?php
// Création du tableau associatif contenant les informations de chaque œuvre
$oeuvres = array(

        ['id' => 1,
        'img' => 'img/clark-van-der-beken.png',
        'alt' => 'Dodomu',
        'title' => 'Dodomu',
        'text' => 'Mia Tozerski est une artiste peintre ukrainienne réfugiée de la guerre. Sur cette œuvre, Dodomu ("domicile" en ukrainien), elle nous montre la tristesse du peuple ukrainien qu\'elle partage, ayant elle-même dû quitter son foyer. L\'œuvre évoque le drapeau liquéfié d\'une Ukraine en souffrance, pleurant la mort de ses compatriotes. Ce travail chargé d\'émotion est le symbole d\'un événement qui marquera l\'Histoire. Cette peinture à l\'acrylique rayonne grâce à son fond lisse et ses mélanges de couleurs éclatantes.',
        'author' => 'Mia Tozerski',
        ],
    
        ['id' => 2,
        'img' => 'img/pawel-czerwinski-3.png', 
        'alt' => 'Aashaaheen Baadal',
        'title' => 'Aashaaheen Baadal',
        'text' => ' Sur cette oeuvre conceptuelle à la fois organique, minérale et liquide, Anaisha Devi nous transporte dans un nuage noir envoûtant. Un sombre tableau qui, par son verni éclatant, rayonne tel un marbre poli. Une oeuvre à la cohérence transcendantale, exécutée à la perfection.',
        'author' => 'Anaisha Devi',
        ],

         ['id' => 3,
            'img' => 'img/dan-cristian-padure.png',
            'alt' => 'Nightlife Traffic',
            'title' => 'Nightlife Traffic',
            'text' => 'Quisque accumsan ultrices ligula vestibulum posuere. Aliquam feugiat ligula eget massa blandit condimentum. Morbi volutpat erat luctus suscipit pellentesque. Quisque cursus tempor nibh at sollicitudin. Sed blandit libero velit. Etiam tincidunt facilisis mollis. Ut mollis nunc sit amet lacinia luctus. Suspendisse volutpat enim semper arcu rutrum, et iaculis risus interdum. Duis at libero.',
            'author' => 'Andrew Forsythe',
        ],

         ['id' => 4,
            'img' => 'img/steve-johnson-5.png', 
            'alt' => 'Le refuge de l\'Havre',
            'title' => 'Le refuge de l\'Havre',
            'text' => ' Nam tempus neque nec felis venenatis auctor. Nam velit risus, lobortis eu quam non, interdum efficitur nibh. Phasellus a augue ac orci lacinia mattis et vel lectus. Sed nec tellus urna. Donec at turpis turpis. Cras quam tellus, imperdiet vitae finibus id, varius quis felis. Maecenas blandit eleifend risus, vel hendrerit erat dignissim id. Nullam at laoreet nibh. Nulla gravida varius sollicitudin. Etiam non aliquam diam, tempor varius sapien. Aenean et velit eu nisi lobortis massa nunc.',
            'author' => 'Simon Pelletier',
         ],

         ['id' => 5,
            'img' => 'img/steve-johnson.png', 
            'alt' => 'Red Washover',
            'title' => 'Red Washover',
            'text' => 'Nunc euismod ullamcorper tortor, id efficitur ante interdum in. Integer eu condimentum nulla. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras viverra suscipit feugiat. Mauris vehicula luctus tellus, eu hendrerit libero laoreet ut. In tristique vehicula nisl in tempus. Morbi tempus aliquet gravida. In eget est congue, rhoncus sapien at, cursus metus.',
            'author' => 'Kit Van Der Borght',
        ],

         ['id' => 6,
            'img' => 'img/pawel-czerwinski.png',  
            'alt' => 'Chromatics',
            'title' => 'Chromatics',
            'text' => 'Vivamus commodo non libero at hendrerit. In lacinia dui sit amet pellentesque iaculis. Donec at ultricies sem porttitor.',
            'author' => 'Jean-Michel Delatronchette',
        ],

         ['id' => 7,
            'img' => 'img/jazmin-quaynor.png', 
            'alt' => 'Digital Negative',
            'title' => 'Digital Negative',
            'text' => 'Integer in nisl posuere, pulvinar ex ac, tincidunt risus. Nullam vel lorem et leo dignissim accumsan. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tempor, magna non consectetur dapibus, est libero iaculis lacus, eget semper turpis orci vitae felis. Fusce eget molestie.',
            'author' => 'Hamish McKee',
        ],

         ['id' => 8,
            'img' => 'img/steve-johnson-6.png',
            'alt' => 'Blast from the past',
            'title' => 'Blast from the past',
            'text' => ' Nunc fermentum purus dapibus justo fermentum auctor. Maecenas non tincidunt leo. Morbi vitae iaculis sem. Donec quis scelerisque massa. Fusce quis accumsan diam, et interdum lectus. Suspendisse mattis pulvinar vehicula. Duis nisi.',
            'author' => 'Juliette Baskerville',
        ],
        
         ['id' => 9,
            'img' => 'img/victor-grabarczyk.png',
            'alt' => 'Hurricane',
            'title' => 'Hurricane',
            'text' => 'Aliquam tristique tempus molestie. Nulla nisl eros, dapibus eu lectus in, cursus accumsan arcu. Suspendisse bibendum diam dignissim porta maximus. Praesent sollicitudin consectetur faucibus. Cras pulvinar massa a orci rutrum, id blandit enim viverra. Praesent sed congue augue. Suspendisse efficitur, nisl quis finibus faucibus, lacus felis bibendum leo, eu euismod lacus mauris in felis. Quisque dignissim et dui et aliquet. Donec ut lobortis eros, vitae tincidunt augue metus.',
            'author' => 'Natalie Wellington',
        ],  

         ['id' => 10,
            'img' => 'img/pawel-czerwinski-2.png', 
            'alt' => 'La marée rouge',
            'title' => 'La marée rouge',
            'text' => ' Vivamus quis odio vel ligula feugiat facilisis. Donec eleifend pellentesque massa, ut malesuada est bibendum sit amet. Morbi tincidunt nec tellus vel ornare. Mauris dolor tellus, gravida eget euismod eu, viverra eget urna. Phasellus feugiat ipsum nec lorem accumsan, sed porta quam dictum massa nunc.',
            'author' => 'Martin Rodriguez',
        ],
        
         ['id' => 11 ,
            'img' => 'img/steve-johnson-2.png', 
            'alt' => 'Asimilacion',
            'title' => 'Asimilacion',
            'text' => ' Mauris ut justo ac mi pretium eleifend. Curabitur sed magna ut elit facilisis pharetra. Maecenas tincidunt fermentum ipsum ut sollicitudin. Nullam feugiat, neque vel egestas sollicitudin, quam leo mattis mauris, in lacinia sem mi id risus. Nullam ultrices quam eu leo auctor tempus. Fusce vestibulum mi ex, vel ultricies purus mollis sollicitudin. Aenean ac vehicula ipsum. Nam turpis ante, ultrices eget odio sed, luctus bibendum mauris sodales sed.',
            'author' => 'Angel Sanchez-Fernandez',
        ],
        
         ['id' => 12,
            'img' => 'img/fly-d.png', 
            'alt' => 'La Galaxia Gialla',
            'title' => 'La Galaxia Gialla',
            'text' => '   Mauris maximus, orci sollicitudin ultrices elementum, tellus neque feugiat leo, quis lobortis purus neque vel lectus. Ut sagittis eros id lectus porttitor tincidunt. Donec scelerisque diam nec felis egestas, eget finibus ante porttitor. Sed malesuada sapien ut semper accumsan. Duis tristique dui vel egestas porttitor. Nunc tristique dapibus orci a amet.',
            'author' => 'Eduardo Tancredi',
        ],

         ['id' => 13,
            'img' => 'img/orfeas-green.png', 
            'alt' => 'Puffy Amalgamate',
            'title' => 'Puffy Amalgamate',
            'text' => ' Donec semper a massa quis congue. In malesuada lorem ligula, ut posuere magna pulvinar in. Proin vitae enim gravida, commodo odio.',
            'author' => 'Sandro De Blasi',
        ],
        
         ['id' => 14,
            'img' => 'img/steve-johnson-4.png',
            'alt' => 'Mirage',
            'title' => 'Mirage',
            'text' => ' Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam iaculis lorem ac ex tristique egestas et nec sapien. Donec tincidunt id erat sit amet tempus. Nullam vel molestie dui. Duis a neque massa. Vivamus quis ornare lacus. Nullam eleifend condimentum egestas. Vivamus magna purus, fermentum mollis mauris sed, consectetur interdum libero. Duis interdum tortor tellus, eget sollicitudin quis.',
            'author' => 'Stéphanie Kaiser',
        ],
        
        ['id' => 15,
            'img' => 'img/steve-johnson-3.png',
            'alt' => 'Blaue Gelbe Muster',
            'title' => 'Blaue Gelbe Muster',
            'text' => 'Curabitur dui odio, porta vel tempor sed, consectetur vitae mi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Orci varius natoque penatibus nec.',
            'author' => 'Adelheid Von Schreiber',
        ],
    );
?>